[package]
name = "iridium"
version = "0.1.0"
authors = ["oky-123 <oky123.ia@gmail.com>"]
edition = "2018"

[dependencies]
nom = "^4.0"
byteorder = "1.3.1"
clap = { version = "2.32", features = ["yaml"] }
